### ISSUE TITLE
fix: package.json links

### ISSUE THREAD

**Issue by dargmuesli** [Talljack/unplugin-remove#1]
Links in the package.json point to https://github.com/antfu, which should be corrected so that the links on https://www.npmjs.com/package/unplugin-remove point to this repository.

**Comment by Talljack** [comment]
> Links in the package.json point to [@antfu](https://github.com/antfu), which should be corrected so that the links on [npmjs.com/package/unplugin-remove](https://www.npmjs.com/package/unplugin-remove) point to this repository.

Thank you, I'll update it.
