### ISSUE TITLE
v0.1.5 is not released to npm

### ISSUE THREAD

**Issue by Mini-ghost** [Talljack/unplugin-remove#2]
This is the current version that can be installed on npm, but according to the github commit, the current version should be `v0.1.5`

<img width="826" alt="截圖 2023-11-07 晚上11 02 33" src="https://github.com/Talljack/unplugin-remove/assets/39984251/b02e35d6-41cd-4416-bb3c-aa9546427acc">

**Comment by Talljack** [comment]
oh, maybe my npm validate error so it doesn't upload successfully. 
I will upload it soon.

**Comment by Talljack** [comment]
I'll do it
<img width="1025" alt="image" src="https://github.com/Talljack/unplugin-remove/assets/34439652/1bc21d68-2b49-4e5e-b92d-d7b13dae3d4e">
