### ISSUE TITLE
Plugin can cause build failure with Vite

### ISSUE THREAD

**Issue by vejja** [Talljack/unplugin-remove#3]
Bug initially reported in Nuxt Security https://github.com/Baroshem/nuxt-security/issues/306

Please see repro and details there

The bug happens when `console.log` is removed from a lambda void-returning arrow-syntax function with a single instruction.

I guess the parser is a bit too aggressive and transforms : 
```
const test = () => console.log('Test')
```
Into 
```
const test = () =>
```
Which is invalid Javascript

**Comment by Talljack** [comment]
fixed in #6
