### ISSUE TITLE
Deprecated dependency in magic-string

### ISSUE THREAD

**Issue by Baroshem** [Talljack/unplugin-remove#7]
Hey Buddy,

One of the users of Nuxt Security (which uses unplugin-remove under the hood for removing loggers functionality) reported that one of the dependencies of nuxt-security - unplugin-remove and more specifically magic-string has a deprecated dependency and it results in a warning.

More details https://github.com/Baroshem/nuxt-security/issues/342#issuecomment-1894122232

I would really appreciate if you could take a look at it as using deprecated dependencies should be avoided in general.

If you need any assistance from my side, please just let me know and I will do my best to help :)

**Comment by Talljack** [comment]
Yep, I'll check the dependencies of Unplugin-remove, specifically of magic-string as soon as possible.
Thanks for you report, if I have problem need you help me, I'll let you know.

**Comment by Talljack** [comment]
I check the `magic-string` replace dependencies of `sourcemap-codec` in 0.27.0, see details for https://github.com/Rich-Harris/magic-string/commit/c87d5eb7f5bece32c2b34480d576cbb190c31971#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L62
Also [sourcemap-codec](https://github.com/Rich-Harris/sourcemap-codec) is deprecated, so I need to upgrade the `magic-string` to [v0.30.5](https://github.com/Rich-Harris/magic-string/releases/tag/v0.30.5) is okay. @Baroshem

**Comment by Talljack** [comment]
fixed #15 
I'll release v0.1.7, you can try it, if have any problem please let me know.

**Comment by Baroshem** [comment]
Thanks @Talljack 

I will bump the package in Nuxt Security and see how it works there :)
