### ISSUE TITLE
ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by vejja** [Talljack/unplugin-remove#8]
Hi,

Another issue was recently reported in Nuxt-Security : https://github.com/Baroshem/nuxt-security/discussions/343

OP is using the following syntax:
```js
false && console.log('.....')
```

Which results in `ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)`

I guess removing the `console.log('.....')` part results in invalid JavaScript:
```js
false &&
```

Suggestion: instead of removing the `console.log('.....')` part, you could maybe replace it with a noop such as `(() => {})()`

**Comment by Talljack** [comment]
yep, I'll consider it.

**Comment by Baroshem** [comment]
Yeah, I think it could make sense to have it as it wouldn't break the code then for users that may utilise this approach.

Let us know @Talljack if we can do anything to help you :)

**Comment by vejja** [comment]
> yep, I'll consider it.

Or, if you don’t want to insert many times the same code snippet, you could override console.log with the same function

**Comment by Talljack** [comment]
fixed #17

**Comment by Baroshem** [comment]
Thanks @Talljack 

I will bump the package in Nuxt Security and see how it works there :)

**Comment by Talljack** [comment]
Yep. Go ahead

Jakub Andrzejewski ***@***.***>于2024年1月19日 周五16:35写道：
